"""Make CPC card number required

Revision ID: dea0c3f2f42b
Revises: c1b3a4604400
Create Date: 2025-08-24 20:36:46.602702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea0c3f2f42b'
down_revision = 'c1b3a4604400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.alter_column('cpc_card_number',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=9),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.alter_column('cpc_card_number',
               existing_type=sa.String(length=9),
               type_=sa.VARCHAR(length=32),
               nullable=True)

    # ### end Alembic commands ###
